### ISSUE TITLE
instance variable @scope_changed not defined

### ISSUE THREAD

**Issue by flyfy1** [solidusio/solidus#1079]
Gemfile:

    source 'https://rubygems.org'

    ruby '2.3.0'

    gem 'rails', '4.2.5.1'
    gem 'pg', '~> 0.15'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'jquery-rails'

    gem 'solidus_core'
    gem 'solidus_api'
    gem 'solidus_backend'

    gem 'solidus_auth_devise'
    gem 'solidus_gateway'

    gem 'jbuilder', '~> 2.0'
    gem 'puma'

    gem 'slim-rails'
    gem 'dotenv-rails'
    gem 'rspec-rails'
    gem 'braintree'

    gem 'rack-cors', :require => 'rack/cors'

    gem 'solidus_product_assembly_api', git: 'git@bitbucket.org:castlery/solidus_product_assembly_api.git', branch: '2-4-stable'

    # Use Capistrano for deployment
    # gem 'capistrano-rails', group: :development

    group :development, :test do
      # Call 'byebug' anywhere in the code to stop execution and get a debugger console
      gem 'byebug'
    end

    group :development do
      gem 'web-console', '~> 2.0'
      gem 'spring'
      gem 'rails-erd', require: false
    end

How to replicate the issue:

1. Create Taxonomies
2. Create Taxon under that
3. Try to edit the Taxon

Issue Log:

    NameError in Spree::Admin::TaxonsController#update
    instance variable @scope_changed not defined

    Rails.root: /Users/songyy/work/Knight

    Application Trace | Framework Trace | Full Trace
    (eval):1:in `remove_instance_variable'
    (eval):1:in `block in make_lambda'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:435:in `instance_exec'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:435:in `block in make_lambda'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:263:in `block in simple'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:506:in `block in call'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:506:in `each'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:506:in `call'
    activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'

**Comment by flyfy1** [comment]
Problem solved after upgrading to `Rails 4.2.6` + `bundle update`
