### ISSUE TITLE
Tests failing on SQLite < 3.8.0

### ISSUE THREAD

**Issue by bbuchalter** [solidusio/solidus#1209]
# API
Steps to reproduce:
```
rm -rf solidus
git clone git@github.com:solidusio/solidus.git
cd solidus
git checkout v1.2
chruby 2.2 # => ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin13]
cd api
bundle
bundle exec rake test_app
bundle exec rspec ./spec/controllers/spree/api/shipments_controller_spec.rb:127
```

Expected a passing test, but got:
```
  1) Spree::Api::ShipmentsController as an admin for completed orders removes a destroyed variant from a shipment
     Failure/Error: expect(response.status).to eq(200)

       expected: 200
            got: 422

       (compared using ==)
     # ./spec/controllers/spree/api/shipments_controller_spec.rb:132:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/bin/rspec:23:in `load'
     # ./vendor/bundle/bin/rspec:23:in `<top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/bin/bundle:23:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/bin/bundle:23:in `<main>'
```

Looking into the log file of the dummy app, I see this error: `columns variant_id, stock_location_id are not unique`
See https://gist.github.com/bbuchalter/1d190501e8d36b586235908244435148 for a full stacktrace.

# Core
Steps to reproduce:
```
rm -rf solidus
git clone git@github.com:solidusio/solidus.git
cd solidus
git checkout v1.2
chruby 2.2 # => ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin13]
cd core
bundle
bundle exec rake test_app
bundle exec rspec spec/models/spree/stock_item_spec.rb:163:159 
spec/models/spree/return_item_spec.rb:118 spec/models/spree/stock_location_spec.rb:254
```

Expected passing tests, but got errors:
```
Run options: include {:focus=>true, :locations=>{"./spec/models/spree/stock_item_spec.rb"=>[163, 159], "./spec/models/spree/return_item_spec.rb"=>[118], "./spec/models/spree/stock_location_spec.rb"=>[254]}}

Randomized with seed 18179
FFFF

Failures:

  1) Spree::ReturnItem#receive! with a stock location when the inventory unit's variant does not yet have a stock item for the stock location it was returned to creates a new stock item for the inventory unit with a count of 1
     Failure/Error: stock_item(vid) || stock_items.create(variant_id: vid)

     ActiveRecord::RecordNotUnique:
       SQLite3::ConstraintException: columns variant_id, stock_location_id are not unique: INSERT INTO "spree_stock_items" ("variant_id", "stock_location_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)
     # ./app/models/spree/stock_location.rb:61:in `stock_item_or_create'
     # ./app/models/spree/stock_location.rb:92:in `move'
     # ./app/models/spree/stock_location.rb:73:in `restock'
     # ./app/models/spree/return_item.rb:230:in `process_inventory_unit!'
     # ./spec/models/spree/return_item_spec.rb:33:in `block (3 levels) in <top (required)>'
     # ./spec/models/spree/return_item_spec.rb:119:in `block (6 levels) in <top (required)>'
     # ./spec/models/spree/return_item_spec.rb:119:in `block (5 levels) in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::ConstraintException:
     #   columns variant_id, stock_location_id are not unique
     #   ./app/models/spree/stock_location.rb:61:in `stock_item_or_create'

  2) Spree::StockLocation#move no stock item exists positive movement creates a stock item
     Failure/Error: stock_item(vid) || stock_items.create(variant_id: vid)

     ActiveRecord::RecordNotUnique:
       SQLite3::ConstraintException: columns variant_id, stock_location_id are not unique: INSERT INTO "spree_stock_items" ("variant_id", "stock_location_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)
     # ./app/models/spree/stock_location.rb:61:in `stock_item_or_create'
     # ./app/models/spree/stock_location.rb:92:in `move'
     # ./spec/models/spree/stock_location_spec.rb:247:in `move'
     # ./spec/models/spree/stock_location_spec.rb:255:in `block (6 levels) in <module:Spree>'
     # ./spec/models/spree/stock_location_spec.rb:255:in `block (5 levels) in <module:Spree>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::ConstraintException:
     #   columns variant_id, stock_location_id are not unique
     #   ./app/models/spree/stock_location.rb:61:in `stock_item_or_create'

  3) Spree::StockItem destroyed doesnt allow recreating more than one stock item at once
     Failure/Error: stock_location.stock_items.create!(variant: subject.variant)

     ActiveRecord::RecordNotUnique:
       SQLite3::ConstraintException: columns variant_id, stock_location_id are not unique: INSERT INTO "spree_stock_items" ("variant_id", "stock_location_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)
     # ./spec/models/spree/stock_item_spec.rb:164:in `block (3 levels) in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::ConstraintException:
     #   columns variant_id, stock_location_id are not unique
     #   ./spec/models/spree/stock_item_spec.rb:164:in `block (3 levels) in <top (required)>'

  4) Spree::StockItem destroyed recreates stock item just fine
     Failure/Error: stock_location.stock_items.create!(variant: subject.variant)

     ActiveRecord::RecordNotUnique:
       SQLite3::ConstraintException: columns variant_id, stock_location_id are not unique: INSERT INTO "spree_stock_items" ("variant_id", "stock_location_id", "created_at", "updated_at") VALUES (?, ?, ?, ?)
     # ./spec/models/spree/stock_item_spec.rb:160:in `block (3 levels) in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
     # /Users/brianb/.gem/ruby/2.2.4/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
     # ------------------
     # --- Caused by: ---
     # SQLite3::ConstraintException:
     #   columns variant_id, stock_location_id are not unique
     #   ./spec/models/spree/stock_item_spec.rb:160:in `block (3 levels) in <top (required)>'

Finished in 2.42 seconds (files took 3.59 seconds to load)
4 examples, 4 failures

Failed examples:

rspec ./spec/models/spree/return_item_spec.rb:118 # Spree::ReturnItem#receive! with a stock location when the inventory unit's variant does not yet have a stock item for the stock location it was returned to creates a new stock item for the inventory unit with a count of 1
rspec ./spec/models/spree/stock_location_spec.rb:254 # Spree::StockLocation#move no stock item exists positive movement creates a stock item
rspec ./spec/models/spree/stock_item_spec.rb:163 # Spree::StockItem destroyed doesnt allow recreating more than one stock item at once
rspec ./spec/models/spree/stock_item_spec.rb:159 # Spree::StockItem destroyed recreates stock item just fine
```

**Comment by bbuchalter** [comment]
After a quick chat with @jhawthorn we identified this as an issue with sqlite3 and partial indexes. From [the docs](https://www.sqlite.org/partialindex.html):

> Partial indexes have been supported in SQLite since version 3.8.0.

If you happen to be running the very old version of sqlite3 that comes with OS X 10.9.5 then these tests will fail.

No plans yet on how to this issue should be addressed, but encouragingly, this should be a _very_ edge case.

**Comment by jhawthorn** [comment]
The issue is the partial index added here, which is treated as a full unique index on sqlite < 3.8
https://github.com/solidusio/solidus/blob/master/core/db/migrate/20151219020209_add_stock_item_unique_index.rb

We can probably use `ActiveRecord::Base.connection.supports_partial_index?` to make this test instead
