### ISSUE TITLE
Migration error from spree 3.0.1 to solidus 1.1.2

### ISSUE THREAD

**Issue by florianguenther** [solidusio/solidus#1247]
upgrading from spree 3.0.1 to solidus 1.1.2 like this

```
bundle exec rails g spree:install --no-seed --no-sample
bundle exec rake db:migrate
```

results in this error

```
-- Fix schema for spree_adjustments order_id column
-- change_table(:spree_adjustments)
-- add_foreign_key(:spree_adjustments, :spree_orders, {:name=>"fk_spree_adjustments_order_id", :column=>:order_id, :on_delete=>:restrict, :on_update=>:restrict})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`az_solidus`.`#sql-5bc_72`, CONSTRAINT `fk_spree_adjustments_order_id` FOREIGN KEY (`order_id`) REFERENCES `spree_orders` (`id`)): ALTER TABLE `spree_adjustments` ADD CONSTRAINT `fk_spree_adjustments_order_id`
FOREIGN KEY (`order_id`)
  REFERENCES `spree_orders` (`id`)
 ON DELETE RESTRICT ON UPDATE RESTRICT/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:45:in `block in change'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:41:in `change'
ActiveRecord::InvalidForeignKey: Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`az_solidus`.`#sql-5bc_72`, CONSTRAINT `fk_spree_adjustments_order_id` FOREIGN KEY (`order_id`) REFERENCES `spree_orders` (`id`)): ALTER TABLE `spree_adjustments` ADD CONSTRAINT `fk_spree_adjustments_order_id`
FOREIGN KEY (`order_id`)
  REFERENCES `spree_orders` (`id`)
 ON DELETE RESTRICT ON UPDATE RESTRICT
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:45:in `block in change'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:41:in `change'
Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails (`az_solidus`.`#sql-5bc_72`, CONSTRAINT `fk_spree_adjustments_order_id` FOREIGN KEY (`order_id`) REFERENCES `spree_orders` (`id`))
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:45:in `block in change'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203069_fix_adjustment_order_id.spree.rb:41:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jhawthorn** [comment]
That's odd. This is failing because there is an adjustment missing an `order_id`. 

This is strange because the [start of this migration](https://github.com/solidusio/solidus/blob/v1.1/core/db/migrate/20150515211137_fix_adjustment_order_id.rb#L6-L37) tries to ensure that all adjustments have an order_id set. Is it possible your database has some adjustments which were tied to a line_item, shipment, or order which no longer exists?

**Comment by florianguenther** [comment]
yes, this was the problem, there are adjustments referencing non existing orders.
thanks
