### ISSUE TITLE
Migration Error with duplicate promotion codes from spree 3.0.1 to solidus 1.1.2

### ISSUE THREAD

**Issue by florianguenther** [solidusio/solidus#1248]
In spree 3.0.1 (and i think also below) it is possible to have multiple promotions with the same code.
Moving to PromotionCodeValues in solidus causes the migration script to fail

```
== 20160614203039 MovePromotionCodeToPromotionCodeValue: migrating ============
-- generating spree_promotion_codes
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Duplicate entry 'R971123724' for key 'index_spree_promotion_codes_on_value': insert into spree_promotion_codes
  (promotion_id, value, created_at, updated_at)
select
  spree_promotions.id,
  spree_promotions.code,
  '2016-06-14 22:35:14',
  '2016-06-14 22:35:14'
from spree_promotions
left join spree_promotion_codes
  on spree_promotion_codes.promotion_id = spree_promotions.id
where (spree_promotions.code is not null and spree_promotions.code <> '') -- promotion has a code
  and spree_promotion_codes.id is null -- a promotion_code hasn't already been created
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:9:in `block in up'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:8:in `up'
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'R971123724' for key 'index_spree_promotion_codes_on_value': insert into spree_promotion_codes
  (promotion_id, value, created_at, updated_at)
select
  spree_promotions.id,
  spree_promotions.code,
  '2016-06-14 22:35:14',
  '2016-06-14 22:35:14'
from spree_promotions
left join spree_promotion_codes
  on spree_promotion_codes.promotion_id = spree_promotions.id
where (spree_promotions.code is not null and spree_promotions.code <> '') -- promotion has a code
  and spree_promotion_codes.id is null -- a promotion_code hasn't already been created
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:9:in `block in up'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:8:in `up'
Mysql2::Error: Duplicate entry 'R971123724' for key 'index_spree_promotion_codes_on_value'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:9:in `block in up'
/Users/schnief/Development/manuel/store-testing/allgaeu-zapf-store/db/migrate/20160614203039_move_promotion_code_to_promotion_code_value.spree.rb:8:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by jhawthorn** [comment]
I'm not sure there's anything we can do about this.

Spree's schema supported having multiple promotions with the same code, but it would not have functioned correctly. It would have applied an arbitrary promotion with a matching code.

At some point, for correctness and safety we needed to add this constraint, I wish we had been more explicit about it in the changelog.

Sorry for the delay in responding.
