### ISSUE TITLE
Cannot process payment created through Importer::Order

### ISSUE THREAD

**Issue by Elffers** [solidusio/solidus#1307]
I need to create a custom checkout flow for a client using Solidus, and I am trying to use an AJAX request to do so in order to have a single-page/single-click checkout UX. 

So, I am trying to create an order by customizing the `API::OrdersController` and using
`Spree::Core::Importer::Order.import(determine_order_user, order_params)`.  I have a Stripe Gateway set up as my latest `Stripe::PaymentMethod` and am passing in the following params as `order_params`:

```
{
  email: 'test@test.com',
  line_items_attributes: {
    "0" => {
      variant_id: 1,
      quantity: 1
    }
  },
  payments_attributes: [{
    payment_method: Spree::PaymentMethod.last.name,
    status: 'checkout',
    source: {
      name: 'Test',
      number: '4242424242424242',
      last_digits: "4242",
      month: 7,
      year: 2017,
      verification_value: 123,
      address_attributes: {
        'zipcode'=> '12345',
      }
    }
  }]
 }
```
I was basing these params off of the specs for the order importer (https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/spec/lib/spree/core/importer/order_spec.rb#L409-L419) and this does successfully create a valid `Spree::Order`, `Spree::Payment`, and `Spree::CreditCard` as the source of the Payment. 

I have the order states set up to be:
```
However, when I try to process the payment either manually or through the backend admin UI, it always fails.

```
Order R457162254 transitioned from cart to payment via next
=> true
irb(main):1468:0> o.next
  Spree::InventoryUnit Load (0.2ms)  SELECT "spree_inventory_units".* FROM "spree_inventory_units" WHERE "spree_inventory_units"."line_item_id" = $1  [["line_item_id", 44]]
  Spree::Shipment Load (0.1ms)  SELECT  "spree_shipments".* FROM "spree_shipments" WHERE "spree_shipments"."id" = $1 LIMIT 1  [["id", 18]]
  Spree::StockLocation Load (0.1ms)  SELECT  "spree_stock_locations".* FROM "spree_stock_locations" WHERE "spree_stock_locations"."id" = $1 LIMIT 1  [["id", 1]]
  Spree::Variant Load (0.1ms)  SELECT  "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."id" = $1 LIMIT 1  [["id", 1]]
   (0.3ms)  SELECT SUM("spree_stock_items"."count_on_hand") FROM "spree_stock_items" INNER JOIN "spree_stock_locations" ON "spree_stock_locations"."id" = "spree_stock_items"."stock_location_id" WHERE "spree_stock_items"."deleted_at" IS NULL AND "spree_stock_items"."variant_id" = 1 AND "spree_stock_items"."stock_location_id" = 1
  Spree::Adjustment Load (0.1ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE "spree_adjustments"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_line_items"."adjustment_total") FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_shipments"."adjustment_total") FROM "spree_shipments" WHERE "spree_shipments"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_adjustments"."amount") FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = $1 AND "spree_adjustments"."adjustable_type" = $2 AND "spree_adjustments"."eligible" = $3  [["adjustable_id", 67], ["adjustable_type", "Spree::Order"], ["eligible", "t"]]
   (0.1ms)  SELECT SUM("spree_line_items"."included_tax_total") FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_shipments"."included_tax_total") FROM "spree_shipments" WHERE "spree_shipments"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_line_items"."additional_tax_total") FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_shipments"."additional_tax_total") FROM "spree_shipments" WHERE "spree_shipments"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_line_items"."promo_total") FROM "spree_line_items" WHERE "spree_line_items"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_shipments"."promo_total") FROM "spree_shipments" WHERE "spree_shipments"."order_id" = $1  [["order_id", 67]]
   (0.1ms)  SELECT SUM("spree_adjustments"."amount") FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_id" = $1 AND "spree_adjustments"."adjustable_type" = $2 AND "spree_adjustments"."source_type" = $3 AND "spree_adjustments"."eligible" = $4  [["adjustable_id", 67], ["adjustable_type", "Spree::Order"], ["source_type", "Spree::PromotionAction"], ["eligible", "t"]]
   (0.1ms)  SELECT COUNT(*) FROM "spree_payments" WHERE "spree_payments"."order_id" = $1 AND ("spree_payments"."state" NOT IN ('failed', 'invalid'))  [["order_id", 67]]
  Spree::Payment Load (0.2ms)  SELECT "spree_payments".* FROM "spree_payments" WHERE "spree_payments"."order_id" = $1  ORDER BY "spree_payments"."created_at" ASC  [["order_id", 67]]
  Spree::PaymentMethod Load (0.1ms)  SELECT  "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = $1 LIMIT 1  [["id", 2]]
  Spree::CreditCard Load (0.1ms)  SELECT  "spree_credit_cards".* FROM "spree_credit_cards" WHERE "spree_credit_cards"."id" = $1 LIMIT 1  [["id", 28]]
   (0.1ms)  BEGIN
  SQL (0.2ms)  UPDATE "spree_payments" SET "state" = $1, "updated_at" = $2 WHERE "spree_payments"."id" = $3  [["state", "invalid"], ["updated_at", "2016-07-06 22:44:32.042489"], ["id", 30]]
  Spree::Order Load (0.1ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."id" = $1 LIMIT 1  [["id", 67]]
  SQL (0.1ms)  UPDATE "spree_orders" SET "updated_at" = '2016-07-06 22:44:32.044089' WHERE "spree_orders"."id" = $1  [["id", 67]]
  SQL (0.1ms)  INSERT INTO "spree_state_changes" ("previous_state", "next_state", "name", "stateful_id", "stateful_type", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["previous_state", "checkout"], ["next_state", "invalid"], ["name", "payment"], ["stateful_id", 30], ["stateful_type", "Spree::Payment"], ["created_at", "2016-07-06 22:44:32.045510"], ["updated_at", "2016-07-06 22:44:32.045510"]]
   (0.9ms)  COMMIT
Order R457162254 halted transition on event payment_failed state payment: State cannot transition via "payment failed"
StateMachines::InvalidTransition: Cannot transition state via :payment_failed from :payment (Reason(s): State cannot transition via "payment failed")
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:224:in `block in add_actions'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
	from /Users/hhh/.gem/ruby/2.3.0/gems/solidus_core-1.3.0/app/models/spree/order/checkout.rb:345:in `process_payments_before_complete'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/eval_helpers.rb:58:in `evaluate_method'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:192:in `block in run_methods'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:191:in `each'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:191:in `run_methods'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/callback.rb:159:in `call'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:364:in `before'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:190:in `block in run_callbacks'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:292:in `block in pausable'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:292:in `catch'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:292:in `pausable'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:190:in `run_callbacks'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:127:in `run_callbacks'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `catch'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:63:in `block in perform'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:186:in `within_transaction'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition_collection.rb:62:in `perform'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/transition.rb:163:in `perform'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:155:in `fire'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:219:in `block in add_actions'
	from /Users/hhh/.gem/ruby/2.3.0/gems/state_machines-0.4.0/lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
	from (irb):1468
	from /Users/hhh/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/hhh/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/hhh/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/hhh/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/hhh/.gem/ruby/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
```

I believe that the issue is there are some gateway credentials that aren't being set on the `Spree::CreditCard` object (https://github.com/solidusio/solidus/blob/60ee1dffc7c3932cd7652cc2b4566f08a12f74b8/core/lib/spree/core/importer/order.rb#L147), but the specs referenced above don't seem to require them in the `order_params`. 

Am I missing a step here?

**Comment by Elffers** [comment]
Update: The issue appeared to be that I was only providing a zip code in the address attributes, but the Payment source that is created (and instance of `Spree::CreditCard`) is associated to an Address object that has validations on the other address fields if any address attribute is found.

So I am now able to correctly process a payment through stripe, but the states are still not accurately reflected in the admin dashboard, which I am assuming has something to do with customizing the state machine.

**Comment by mamhoff** [comment]
I'm not sure it's necessary to pass an address to the credit card. The order has a billing address, and ideally the credit card should just take that over (I'm assuming you're not dealing with split payments nor are you assuming people pay with a credit card where the bill address is different from the order's bill address). TLDR: Try not providing address attributes on the credit card.

**Comment by seand7565** [comment]
It doesn't seem like there's anything to do in this issue - candidate for closure?
