### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by kennyadsl** [solidusio/solidus#1491]
I'm having this error while running ./build.sh:

```bash
bash build.sh
Setup Spree defaults and creating test application...
Resolving dependencies....
The Gemfile's dependencies are satisfied
rake test_app
Generating dummy Rails application...
Database 'spree/api_spree_test' already exists
Setting up dummy database...
bundle exec rake db:migrate VERBOSE=false
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "index_products_promotion_rules_on_product_id" already exists
: CREATE  INDEX  "index_products_promotion_rules_on_product_id" ON "spree_products_promotion_rules"  ("product_id")
/Users/user/Code/open-source/solidus/api/spec/dummy/db/migrate/20161001084919_spree_promo_one_two.spree.rb:12:in `up'
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "index_products_promotion_rules_on_product_id" already exists
: CREATE  INDEX  "index_products_promotion_rules_on_product_id" ON "spree_products_promotion_rules"  ("product_id")
/Users/user/Code/open-source/solidus/api/spec/dummy/db/migrate/20161001084919_spree_promo_one_two.spree.rb:12:in `up'
PG::DuplicateTable: ERROR:  relation "index_products_promotion_rules_on_product_id" already exists
/Users/user/Code/open-source/solidus/api/spec/dummy/db/migrate/20161001084919_spree_promo_one_two.spree.rb:12:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [bundle exec rake db:migrate VERBOSE=false...]
/Users/user/Code/open-source/solidus/core/lib/spree/testing_support/common_rake.rb:20:in `block (2 levels) in <top (required)>'
/Users/user/Code/open-source/solidus/api/Rakefile:15:in `block in <top (required)>'
Tasks: TOP => common:test_app
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [rake test_app...]
/Users/user/Code/open-source/solidus/Rakefile:24:in `block (3 levels) in <top (required)>'
/Users/user/Code/open-source/solidus/Rakefile:23:in `chdir'
/Users/user/Code/open-source/solidus/Rakefile:23:in `block (2 levels) in <top (required)>'
/Users/user/Code/open-source/solidus/Rakefile:22:in `each'
/Users/user/Code/open-source/solidus/Rakefile:22:in `block in <top (required)>'
Tasks: TOP => test_app
(See full trace by running task with --trace)
```

I think the issue is related to an already existing database for test apps. One of the first lines is:

```bash
Database 'spree/api_spree_test' already exists
```

and then, when it tries to run migrations, I have some `PG::DuplicateTable: ERROR`.

To fix it I had to change this line into:

```ruby
sh "RAILS_ENV=test bin/rails db:environment:set"
sh "RAILS_ENV=test bundle exec rake db:drop"
sh "RAILS_ENV=test bundle exec rake db:create"
sh "RAILS_ENV=test bundle exec rake db:migrate VERBOSE=false" 
```

I understand that this can be fixed just cleaning all the test apps databases (and often also the Gemfile.lock). So is there a task you guys run to perform this cleanup? Wouldn't be a good idea to run these cleanups into the build script?

**Comment by jhawthorn** [comment]
We should absolutely do this in our `test_app` task.

I may have broken this in bc8efcb5f66057e0a6e91abaf801528c556d28d0, but reverting that doesn't fix the issue. Rails 5's environment tracking seems to throw a wrench into the works also.
