### ISSUE TITLE
NoMethodError: undefined methods `helper_method' & `layout` for Spree::BaseController:Class

### ISSUE THREAD

**Issue by anulman** [solidusio/solidus#1665]
When implementing `solidus_core` in a Rails 5 `rails-api` project, Solidus throws the above errors on boot and aborts, instead of properly booting.

Seems like this impacts several libs relying on `AbstractController::HelperMethods.helper_method` and `ActionView::Layouts.layout`, and that the Rails team will not likely add these back to the main lib. Instead, they recommend not calling these methods if not available, e.g. https://github.com/rails-api/rails-api/issues/6

Overriding these with e.g. the following allows boot to progress:
```
class ApplicationController < ActionController::API
  class << self
    def helper_method *meths
      # todo: rm once solidus resolves `helper_method` issue
    end

    def layout layout, conditions = {}
      # todo: rm once solidus resolves `layout` issue
    end
  end

# ...
end
```

Full trace (helper_method):
```
NoMethodError: undefined method `helper_method' for Spree::BaseController:Class
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.0/lib/spree/core/controller_helpers/auth.rb:16:in `block in <module:Auth>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.0/app/controllers/spree/base_controller.rb:5:in `include'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.0/app/controllers/spree/base_controller.rb:5:in `<class:BaseController>'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.0/app/controllers/spree/base_controller.rb:4:in `<top (required)>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:380:in `block in require_or_load'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `each'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `each'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `eager_load!'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:354:in `eager_load!'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `each'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
  /var/www/api/releases/2/config/environment.rb:3:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:315:in `load_rackup'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:243:in `app'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:127:in `load_and_bind'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
  /var/www/api/releases/2/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<top (required)>'
```

Full trace (layout):
```
NoMethodError: undefined method `layout' for Spree::BaseController:Class
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.1/lib/spree/core/controller_helpers/common.rb:11:in `block in <module:Common>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.1/app/controllers/spree/base_controller.rb:7:in `include'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.1/app/controllers/spree/base_controller.rb:7:in `<class:BaseController>'
  /var/www/api/shared/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.0.1/app/controllers/spree/base_controller.rb:4:in `<top (required)>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:380:in `block in require_or_load'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:336:in `depend_on'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:252:in `require_dependency'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `each'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:475:in `block in eager_load!'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `each'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:473:in `eager_load!'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:354:in `eager_load!'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `each'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
  /var/www/api/releases/6/config/environment.rb:3:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:315:in `load_rackup'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/configuration.rb:243:in `app'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/runner.rb:127:in `load_and_bind'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/single.rb:85:in `run'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/launcher.rb:172:in `run'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/lib/puma/cli.rb:74:in `run'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/gems/puma-3.6.2/bin/puma:10:in `<top (required)>'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/bin/puma:22:in `load'
  /var/www/api/releases/6/vendor/bundle/ruby/2.3.0/bin/puma:22:in `<top (required)>'
```

**Comment by cbrunsdon** [comment]
Looking through the devise PR (and every other PR that references it), it does look like wrapping it in a respond_to? check is the community preferred way of solving the issue.

https://github.com/plataformatec/devise/pull/3732

**Comment by anulman** [comment]
@cbrunsdon 👍 that looks like the right approach for the lib. My "resolution" code was purely in case other consumers stumble on this issue while debugging :)

Happy to submit a PR if this will be as simple as find/replace'ing through the project and confirming all tests continue to pass. If add'l tests will be required (not sure if this qualifies as refactoring vs. bug fix?), I'd appreciate some additional guidance.

**Comment by cbrunsdon** [comment]
@anulman I don't personally think any additional tests should be required for this, though eventually we might want to rails-api spec in place (not sure how that would look).

A pr with just the surrounding respond_to? check would be fantastic, thanks.

**Comment by anulman** [comment]
@cbrunsdon first stab, haven't been able to get `build.sh` running. Can any project devs help? I've consulted README.md & CONTRIBUTING.md and am having difficulty getting the first test run booted.

Dumping state:

- Failed due to missing mysql executable; `brew install mysql`
- Failed due to postgres not running; `pg_ctl start` (why are both dbs required?)
- Failed due to missing postgres role; `CREATE ROLE postgres SUPERUSER;`
- Failed due to inability to log postgres user into database; unsure how to proceed
