### ISSUE TITLE
v2.2.0.rc1 on heroku 

### ISSUE THREAD

**Issue by AndreiMotinga** [solidusio/solidus#1849]
2017-04-20T21:31:27.611193+00:00 app[web.1]: ! Unable to load application: NameError: uninitialized constant Spree::ApplicationMailer
2017-04-20T21:31:27.611279+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2017-04-20T21:31:27.611348+00:00 app[web.1]: NameError: uninitialized constant Spree::ApplicationMailer
2017-04-20T21:31:27.611349+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.2.0.rc1/app/mailers/spree/promotion_code_batch_mailer.rb:2:in `<module:Spree>'
2017-04-20T21:31:27.611349+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.2.0.rc1/app/mailers/spree/promotion_code_batch_mailer.rb:1:in `<top (required)>'
2017-04-20T21:31:27.611350+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2017-04-20T21:31:27.611350+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2017-04-20T21:31:27.611351+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
2017-04-20T21:31:27.611354+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
2017-04-20T21:31:27.611354+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
2017-04-20T21:31:27.611355+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
2017-04-20T21:31:27.611355+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `each'
2017-04-20T21:31:27.611356+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `block in eager_load!'
2017-04-20T21:31:27.611356+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `each'
2017-04-20T21:31:27.611357+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `eager_load!'
2017-04-20T21:31:27.611357+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:354:in `eager_load!'
2017-04-20T21:31:27.611358+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `each'
2017-04-20T21:31:27.611358+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
2017-04-20T21:31:27.611359+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
2017-04-20T21:31:27.611359+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
2017-04-20T21:31:27.611360+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
2017-04-20T21:31:27.611360+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
2017-04-20T21:31:27.611361+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2017-04-20T21:31:27.611361+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
2017-04-20T21:31:27.611361+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
2017-04-20T21:31:27.611362+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
2017-04-20T21:31:27.611362+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
2017-04-20T21:31:27.611363+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
2017-04-20T21:31:27.611363+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
2017-04-20T21:31:27.611363+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
2017-04-20T21:31:27.611364+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
2017-04-20T21:31:27.611364+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
2017-04-20T21:31:27.611364+00:00 app[web.1]:   /app/config/environment.rb:5:in `<top (required)>'
2017-04-20T21:31:27.611365+00:00 app[web.1]:   config.ru:1:in `require'
2017-04-20T21:31:27.611366+00:00 app[web.1]:   config.ru:1:in `block in <main>'
2017-04-20T21:31:27.611366+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
2017-04-20T21:31:27.611366+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
2017-04-20T21:31:27.611367+00:00 app[web.1]:   config.ru:in `new'
2017-04-20T21:31:27.611367+00:00 app[web.1]:   config.ru:in `<main>'
2017-04-20T21:31:27.611367+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
2017-04-20T21:31:27.611368+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
2017-04-20T21:31:27.611368+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
2017-04-20T21:31:27.611368+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
2017-04-20T21:31:27.611369+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
2017-04-20T21:31:27.611369+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
2017-04-20T21:31:27.611370+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
2017-04-20T21:31:27.611370+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
2017-04-20T21:31:27.611370+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
2017-04-20T21:31:27.611370+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
2017-04-20T21:31:27.611373+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
2017-04-20T21:31:27.611373+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'

**Comment by kennyadsl** [comment]
Hi @AndreiMotinga, can you please refer to [this guide](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#filing-an-issue) when posting issues? It will help other people understand your problem and help you, thanks!

**Comment by jhawthorn** [comment]
Thanks for the report. Looks like `PromotionCodeBatchMailer` was inheriting from `ApplicationMailer`, whereas all previous mailers inherited from `Spree::BaseMailer`.

**Comment by jhawthorn** [comment]
This is fixed by #1854, which will be included in 2.2.0
