### ISSUE TITLE
Can't start solidus on heroku 

### ISSUE THREAD

**Issue by AndreiMotinga** [solidusio/solidus#1868]
### heroku log
```
2017-04-28T16:51:57.445428+00:00 heroku[web.1]: Process exited with status 1
2017-04-28T16:51:57.457545+00:00 heroku[web.1]: State changed from starting to crashed
2017-04-28T16:51:57.311067+00:00 app[web.1]: ! Unable to load application: NameError: uninitialized constant Spree::ApplicationMailer
2017-04-28T16:51:57.311206+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2017-04-28T16:51:57.311294+00:00 app[web.1]: NameError: uninitialized constant Spree::ApplicationMailer
2017-04-28T16:51:57.311296+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.2.0.rc1/app/mailers/spree/promotion_code_batch_mailer.rb:2:in `<module:Spree>'
2017-04-28T16:51:57.311297+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/solidus_core-2.2.0.rc1/app/mailers/spree/promotion_code_batch_mailer.rb:1:in `<top (required)>'
2017-04-28T16:51:57.311298+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2017-04-28T16:51:57.311298+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
2017-04-28T16:51:57.311300+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
2017-04-28T16:51:57.311299+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
2017-04-28T16:51:57.311302+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `each'
2017-04-28T16:51:57.311300+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
2017-04-28T16:51:57.311301+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
2017-04-28T16:51:57.311302+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:475:in `block in eager_load!'
2017-04-28T16:51:57.311303+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `each'
2017-04-28T16:51:57.311304+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:473:in `eager_load!'
2017-04-28T16:51:57.311305+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `each'
2017-04-28T16:51:57.311305+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/engine.rb:354:in `eager_load!'
2017-04-28T16:51:57.311306+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
2017-04-28T16:51:57.311306+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
2017-04-28T16:51:57.311307+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
2017-04-28T16:51:57.311308+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
2017-04-28T16:51:57.311309+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
2017-04-28T16:51:57.311309+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2017-04-28T16:51:57.311310+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
2017-04-28T16:51:57.311310+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
2017-04-28T16:51:57.311312+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
2017-04-28T16:51:57.311311+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
2017-04-28T16:51:57.311312+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
2017-04-28T16:51:57.311313+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
2017-04-28T16:51:57.311314+00:00 app[web.1]:   /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
2017-04-28T16:51:57.311314+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
2017-04-28T16:51:57.311315+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
2017-04-28T16:51:57.311315+00:00 app[web.1]:   /app/config/environment.rb:5:in `<top (required)>'
2017-04-28T16:51:57.311316+00:00 app[web.1]:   config.ru:1:in `require'
2017-04-28T16:51:57.311317+00:00 app[web.1]:   config.ru:1:in `block in <main>'
2017-04-28T16:51:57.311317+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
2017-04-28T16:51:57.311318+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
2017-04-28T16:51:57.311319+00:00 app[web.1]:   config.ru:in `new'
2017-04-28T16:51:57.311319+00:00 app[web.1]:   config.ru:in `<main>'
2017-04-28T16:51:57.311320+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
2017-04-28T16:51:57.311320+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
2017-04-28T16:51:57.311321+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
2017-04-28T16:51:57.311322+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
2017-04-28T16:51:57.311322+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
2017-04-28T16:51:57.311323+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
2017-04-28T16:51:57.311325+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
2017-04-28T16:51:57.311324+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
2017-04-28T16:51:57.311326+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
2017-04-28T16:51:57.311325+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
2017-04-28T16:51:57.311330+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `load'
2017-04-28T16:51:57.311331+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
```

### Expected behavior
It starts and works ok in development but not on heroku

### Gemfile
```
source "https://rubygems.org"
ruby "2.3.1"

gem "autoprefixer-rails"
gem "delayed_job_active_record"
gem "flutie"
gem "jquery-rails"
gem "pg"
gem "puma"
gem "rack-canonical-host"
gem "rails", "~> 5.0.2"
gem "recipient_interceptor"
gem "sass-rails", "~> 5.0"
gem "sprockets", ">= 3.0.0"
gem "uglifier"

gem "aws-sdk"

gem 'solidus', '~> 2.2.0.rc1'
gem "solidus_auth_devise"
gem "solidus_i18n", github: "solidusio-contrib/solidus_i18n", branch: "master"
gem "globalize", github: "globalize/globalize"
gem "solidus_globalize", github: "solidusio-contrib/solidus_globalize"

gem "material_design_lite-rails", "~> 1.3"
gem "material_icons"
gem "slim-rails"

group :development do
  gem 'guard-livereload', '~> 2.5', require: false
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bullet"
  gem "bundler-audit", ">= 0.5.0", require: false
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails", "~> 3.5.0.beta4"
end

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

group :test do
  gem "capybara-webkit"
  gem "database_cleaner"
  gem "formulaic"
  gem "launchy"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "timecop"
  gem "webmock"
end

group :staging, :production do
  gem "rack-timeout"
  gem "rails_stdout_logging"
end
```

**Comment by softr8** [comment]
Try updating Solidus: https://github.com/solidusio/solidus/commit/03a48593b195d3f5e7b87f6cfd2818a5ef25375b

**Comment by AndreiMotinga** [comment]
@softr8, that indeed helped, thank you. I should have figured it out myself.  
I wasn't expecting it, since I got other app ( new and clean) without this problem, so my guess was that it's cause of some bad data. 
I'm guessing, maybe cause this old/broken app has some mailers in it, and other doesn't... 

Anyhow, thank you.
