### ISSUE TITLE
Heroku one-click deploy not working

### ISSUE THREAD

**Issue by husam212** [solidusio/solidus#1910]
### Build log
```
-----> Ruby app detected
-----> Compiling Ruby/Rails
       Compiling solidus
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
logger: unrecognized option '--no-ri'
Usage:
 logger [options] [<message>]
Enter messages into the system log.
Options:
 -i                       log the logger command's PID
     --id[=<id>]          log the given <id>, or otherwise the PID
 -f, --file <file>        log the contents of this file
 -e, --skip-empty         do not log empty lines when processing files
     --no-act             do everything except the write the log
 -p, --priority <prio>    mark given message with this priority
     --octet-count        use rfc6587 octet counting
     --prio-prefix        look for a prefix on every line read from stdin
 -s, --stderr             output message to standard error as well
 -S, --size <size>        maximum size for a single message
 -t, --tag <tag>          mark every line with this tag
 -n, --server <name>      write to this remote syslog server
 -P, --port <number>      use this UDP port
 -T, --tcp                use TCP only
 -d, --udp                use UDP only
     --rfc3164            use the obsolete BSD syslog protocol
     --rfc5424[=<snip>]   use the syslog protocol (the default for remote);
                            <snip> can be notime, or notq, and/or nohost
     --msgid <msgid>      set rfc5424 message id field
 -u, --socket <socket>    write to this Unix socket
     --socket-errors[=<on|off|auto>]
                          print connection errors when using Unix sockets
     --journald[=<file>]  write journald entry
 -h, --help     display this help and exit
 -V, --version  output version information and exit
For more details see logger(1).
 !
 !     "NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install --no-ri --no-rdoc railties:'~>5.0.1'" failed
 !
/app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/solidus.rb:88:in `sh': "NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install --no-ri --no-rdoc railties:'~>5.0.1'" failed (RuntimeError)
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/solidus.rb:26:in `compile'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:16:in `block (2 levels) in <main>'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/base.rb:131:in `log'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:15:in `block in <main>'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:35:in `block in trace'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:11:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by RostislavKorin** [comment]
same issue

**Comment by blairanderson** [comment]
looks like i'm having this as well. 


```
-----> Ruby app detected
-----> Compiling Ruby/Rails
       Compiling solidus
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
logger: unrecognized option '--no-ri'
Usage:
 logger [options] [<message>]
Enter messages into the system log.
Options:
 -i                       log the logger command's PID
     --id[=<id>]          log the given <id>, or otherwise the PID
 -f, --file <file>        log the contents of this file
 -e, --skip-empty         do not log empty lines when processing files
     --no-act             do everything except the write the log
 -p, --priority <prio>    mark given message with this priority
     --octet-count        use rfc6587 octet counting
     --prio-prefix        look for a prefix on every line read from stdin
 -s, --stderr             output message to standard error as well
 -S, --size <size>        maximum size for a single message
 -t, --tag <tag>          mark every line with this tag
 -n, --server <name>      write to this remote syslog server
 -P, --port <number>      use this UDP port
 -T, --tcp                use TCP only
 -d, --udp                use UDP only
     --rfc3164            use the obsolete BSD syslog protocol
     --rfc5424[=<snip>]   use the syslog protocol (the default for remote);
                            <snip> can be notime, or notq, and/or nohost
     --msgid <msgid>      set rfc5424 message id field
 -u, --socket <socket>    write to this Unix socket
     --socket-errors[=<on|off|auto>]
                          print connection errors when using Unix sockets
     --journald[=<file>]  write journald entry
 -h, --help     display this help and exit
 -V, --version  output version information and exit
For more details see logger(1).
 !
 !     "NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install --no-ri --no-rdoc railties:'~>5.0.1'" failed
 !
/app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/solidus.rb:88:in `sh': "NOKOGIRI_USE_SYSTEM_LIBRARIES=1 gem install --no-ri --no-rdoc railties:'~>5.0.1'" failed (RuntimeError)
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/solidus.rb:26:in `compile'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:16:in `block (2 levels) in <main>'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/base.rb:131:in `log'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:15:in `block in <main>'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:35:in `block in trace'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/4503e3a76977915f47253edc22ff766cf41874cec155814eeb2bed137037cc920729733d948ffeb2124e6612e9bfcc160ea3849de67fe7190e0f7d126454c288/bin/compile:11:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by jhawthorn** [comment]
This needed some small updates due to a change in heroku, as well as needed to be updated to support Rails 5.1. Should be working again, I was able to deploy https://solidus-rails-51-test.herokuapp.com/
