### ISSUE TITLE
Remove Environment from Spree::Tracker

### ISSUE THREAD

**Issue by BenMorganIO** [solidusio/solidus#231]
While doing a transition from Spree 3 --> Solidus I received this error in specs:

```ruby
     Failure/Error: visit cart_path
     ActionView::Template::Error:
       PG::UndefinedColumn: ERROR:  column spree_trackers.environment does not exist
       LINE 1: ...rackers" WHERE "spree_trackers"."active" = $1 AND "spree_tra...
                                                                    ^
       : SELECT  "spree_trackers".* FROM "spree_trackers" WHERE "spree_trackers"."active" = $1 AND "spree_trackers"."environment" = 'test'  ORDER BY "spree_trackers"."id" ASC LIMIT 1
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare_statement'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `exec_cache'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation.rb:638:in `exec_queries'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation.rb:514:in `load'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation.rb:243:in `to_a'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation/finder_methods.rb:127:in `first'
     # /Users/BenAMorgan/.rvm/gems/ruby-2.2.2/bundler/gems/solidus-f26f31b83c2e/core/app/models/spree/tracker.rb:4:in `current'
     # ./app/helpers/application_helper.rb:19:in `current_tracker'
```

I'll get a PR in very soon to address this issue.

**Comment by cbrunsdon** [comment]
I'm killing this in favor of #232
