### ISSUE TITLE
uninitialized constant Spree::Admin with Bootsnap

### ISSUE THREAD

**Issue by damienlethiec** [solidusio/solidus#2679]
Hello,

I have just created a new rails 5.1 app and installed Solidus. Unfortunately, I have a problem with bootsnap. When I disable bootsnap, the problem goes away and Solidus works fine.

Thanks a ton in advance :)

### Steps to reproduce
- Create a Rails 5.1.6 app
- Change the Bootsnap gem in your gemfile to `gem 'bootsnap', github: 'ojab/bootsnap', require: false` (to solve another bug)
- Install Solidus (as in the Github repo)
- Launch `rails s`

### Expected behavior
The app launches correctly

### Actual behavior
Error:

```
	85: from bin/rails:3:in `<main>'
	84: from bin/rails:3:in `load'
	83: from /Users/damienlethiec/code/damienlethiec/ProjetsPros/Carole/conscientsV2/bin/spring:15:in `<top (required)>'
	82: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	81: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	80: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	79: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	78: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	77: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	76: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	75: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	74: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	73: from /Users/damienlethiec/code/damienlethiec/ProjetsPros/Carole/conscientsV2/bin/rails:9:in `<top (required)>'
	72: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	71: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	70: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	69: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	68: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	67: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<main>'
	66: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	65: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	64: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	63: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	62: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	61: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	60: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	59: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	58: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:42:in `start'
	57: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	56: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
	55: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:24:in `app'
	54: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
	53: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	52: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
	51: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
	50: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
	49: from config.ru:in `<main>'
	48: from config.ru:in `new'
	47: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
	46: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
	45: from config.ru:5:in `block in <main>'
	44: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require_relative'
	43: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	42: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	41: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	40: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	39: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	38: from /Users/damienlethiec/code/damienlethiec/ProjetsPros/Carole/conscientsV2/config/environment.rb:7:in `<main>'
	37: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
	36: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
	35: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	34: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	33: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	32: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	31: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	30: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	29: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	28: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	27: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	26: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
	25: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
	24: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	23: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
	22: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/reloader.rb:87:in `prepare!'
	21: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:130:in `run_callbacks'
	20: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `invoke_before'
	19: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `each'
	18: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:507:in `block in invoke_before'
	17: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:198:in `block in halting'
	16: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `block in default_terminator'
	15: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:600:in `catch'
	14: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
	13: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
	12: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
	11: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `instance_exec'
	10: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:21:in `block in <class:Engine>'
	 9: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:33:in `prepare_backend'
	 8: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:33:in `glob'
	 7: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/solidus_auth_devise-2.1.0/lib/spree/auth/engine.rb:34:in `block in prepare_backend'
	 6: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 5: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 4: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/gems/solidus_auth_devise-2.1.0/lib/controllers/backend/spree/admin/admin_controller_decorator.rb:1:in `<main>'
	 3: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
	 2: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
	 1: from /usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/bootsnap-4eb38c800af6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant Spree::Admin (NameError)
```

### System configuration
**Solidus Version**:
- 2.5.0

**Extensions in use**:
- Bootsnap, github version

**Comment by ccarruitero** [comment]
Hi @damienlethiec 

This seems to be a issue with bootsnap and not with solidus. There is a similar issue in bootsnap repository's issue tracker https://github.com/Shopify/bootsnap/issues/147
