### ISSUE TITLE
Rails 5.2.2 and Ransack

### ISSUE THREAD

**Issue by deepaksisodiaa** [solidusio/solidus#2987]
I am getting this error after add both gems "solidus", "solidus_auth_devise" when run "bundle exec rails g spree:install"

```


home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association (LoadError)
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/polyamorous.rb:18:in `block in <main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/polyamorous.rb:17:in `each'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/polyamorous.rb:17:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/ransack/adapters/active_record/context.rb:2:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/ransack/adapters/active_record.rb:14:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/ransack/adapters.rb:25:in `require_adapter'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/ransack-2.1.0/lib/ransack.rb:27:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/lib/spree/core.rb:13:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/lib/spree_core.rb:3:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/solidus_core-2.7.0/lib/solidus_core.rb:3:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/solidus-2.7.0/lib/solidus.rb:3:in `<main>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	from /home/deepak/mystore/config/application.rb:7:in `<top (required)>'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /home/deepak/.rvm/gems/ruby-2.5.3/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/deepak/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/deepak/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'


```

**Comment by kennyadsl** [comment]
Thanks for reporting. This happened yesterday after the Rails 5.2.2 release and it's a [known issue](https://github.com/activerecord-hackery/ransack/issues/987). 

[They will cut a release soon.](https://github.com/activerecord-hackery/ransack/pull/985#issuecomment-444208837)

**Comment by tvdeyen** [comment]
Ransack 2.1.1 is out.

**Comment by deepaksisodiaa** [comment]
after solving this error i am getting this error "`alias_method': undefined method `apply_free_shipping_promotions' for class `#<Class:0x000000000413c230>' (NameError)"

when i am trying to run "bundle exec rails g spree:install"

**Comment by kennyadsl** [comment]
@deepaksisodiaa please follow https://github.com/solidusio/solidus/issues/2989

I think we can close this one
