### ISSUE TITLE
sqlite3 dependency version conflicts with activerecord sqlite adapter

### ISSUE THREAD

**Issue by mdesantis** [solidusio/solidus#3087]
On February 04, 2019 sqlite3 1.4.0 has been released. This version breaks ActiveRecord 5.2.2 SQLite adapter, which requires sqlite3 ~> 1.3.6: https://github.com/rails/rails/blob/v5.2.2/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L12

**Solidus Version**: `2.9.0.alpha@a736ec34e`

**To Reproduce**

1. Checkout Solidus repo
2. Run `bundle exec rake sandbox`

**Current behavior**

It fails showing the following error:

```
rake aborted!
LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
/home/maurizio/Sviluppo/Nebulab/solidus/sandbox/config/environment.rb:5:in `<main>'
/home/maurizio/.asdf/installs/ruby/2.6.0/bin/bundle:23:in `load'
/home/maurizio/.asdf/installs/ruby/2.6.0/bin/bundle:23:in `<main>'

Caused by:
Gem::LoadError: can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
/home/maurizio/Sviluppo/Nebulab/solidus/sandbox/config/environment.rb:5:in `<main>'
/home/maurizio/.asdf/installs/ruby/2.6.0/bin/bundle:23:in `load'
/home/maurizio/.asdf/installs/ruby/2.6.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:drop => db:load_config => environment
(See full trace by running task with --trace)
```

**Expected behavior**

It should successfully create the sandbox

**Comment by mdesantis** [comment]
Fixing PR on its way
