### ISSUE TITLE
install generator hang indefinitely

### ISSUE THREAD

**Issue by AdrienGiboire** [solidusio/solidus#3288]
I am trying to install solidus in an existing project running on Rails 5.2.3.
Solidus version installed is 2.9.0.

When running any generators, e.g. `bundle exec rails g spree:install`, I run into an issue:

```
/home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant Spree::Admin::ReportsController (NameError)
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
        from /home/dev/.gem/ruby/2.5.5/gems/solidus_marketplace-0.1.0/app/controllers/spree/admin/reports_controller_decorator.rb:3:in `<top (required)>'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
        from /home/dev/.gem/ruby/2.5.5/gems/solidus_marketplace-0.1.0/lib/solidus_marketplace/engine.rb:46:in `block in activate'
        from /home/dev/.gem/ruby/2.5.5/gems/solidus_marketplace-0.1.0/lib/solidus_marketplace/engine.rb:45:in `glob'
        from /home/dev/.gem/ruby/2.5.5/gems/solidus_marketplace-0.1.0/lib/solidus_marketplace/engine.rb:45:in `activate'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
        from /home/dev/.gem/ruby/2.5.5/gems/activesupport-5.2.3/lib/active_support/reloader.rb:89:in `prepare!'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /home/dev/.rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/dev/.gem/ruby/2.5.5/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
        from /home/dev/code/123courses/config/environment.rb:5:in `<top (required)>'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
        from /home/dev/.gem/ruby/2.5.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
        from /home/dev/.gem/ruby/2.5.5/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from -e:1:in `require'
        from -e:1:in `<main>'
```

**Solidus Version**:
2.9.0

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5

**Additional context**
gemfile & gemfile.lock https://gist.github.com/AdrienGiboire/3ea0a7f49e99ef97fb3228f20ab8aed8

**Comment by ccarruitero** [comment]
Hi @AdrienGiboire, until I can see this isn't a problem with solidus.

You are using `solidus_marketplace`, and this gem attempt to monkey patch `Spree::Admin::ReportsController`.

The report controller and views was extracted into [solidus_reports](https://github.com/solidusio-contrib/solidus_reports) some time ago. So you will be good by adding that gem

**Comment by kennyadsl** [comment]
Yes, as @ccarruitero it's a `solidus_marketplace` issue. It should monkey patch that controller only if it exists, or it should require `solidus_reports` as a dependency.
