### ISSUE TITLE
Error running test app on master (ManifestNeededError)

### ISSUE THREAD

**Issue by pelargir** [solidusio/solidus#3376]
I'm trying to run the test app on the latest master branch but I'm getting an error about a missing manifest.

**Solidus Version**:

**To Reproduce**
Run this from the project root: `bundle exec rake test_app`

**Current behavior**
I see the following output:

```
-----------
Solidus api
-----------
rake db:reset
Dropped database 'db/solidus_api_test.sqlite3'
Created database 'db/solidus_api_test.sqlite3'

---------------
Solidus backend
---------------
rake db:reset
rake aborted!
Sprockets::Railtie::ManifestNeededError: Expected to find a manifest file in `app/assets/config/manifest.js`
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/railtie.rb:190:in `public_send'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/railties-6.0.0/lib/rails/railtie.rb:190:in `method_missing'
/Users/pelargir/Projects/candlescience/solidus/core/lib/spree/testing_support/dummy_app.rb:43:in `setup'
/Users/pelargir/Projects/candlescience/solidus/core/lib/spree/testing_support/dummy_app/rake_tasks.rb:12:in `block in initialize'
/Users/pelargir/.rvm/gems/ruby-2.6.5/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
/Users/pelargir/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/pelargir/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:reset => db:drop => dummy_environment
(See full trace by running task with --trace)
rake aborted!
```

**Expected behavior**
The test app should launch without any errors.

**Desktop**
 - OS: Mac OS Catalina (10.15)
 - Browser: Chrome
 - Version: 77.0

**Comment by kennyadsl** [comment]
This is related to #3374, you could temporarily lock sprockets to version 3.x in the meantime to make specs pass.

**Comment by pelargir** [comment]
Thank you.
