### ISSUE TITLE
Cannot configure paperclip 

### ISSUE THREAD

**Issue by Shalashtein** [solidusio/solidus#3878]
Hi, I've been trying to configure paperclip to store the images on cloudinary

I installed the [Cloudinary-Paperclip gem](https://github.com/GoGoCarl/paperclip-cloudinary), and configured my API keys

Then I needed to tell paperclip to store on cloudinary but whenever I try to do so the configuration is overriden by the Solidus defaults. I created a decorator for the `Spree::Image::PaperclipAttachment` class and added the following:

```
module Spree::Image::PaperclipAttachmentDecorator
  def self.prepended(base)
    included(base) do
      validate :no_attachment_errors
      has_attached_file :attachment,
                        styles: { mini: '48x48>', small: '400x400>', product: '680x680>', large: '1200x1200>' },
                        default_style: :product,
                        default_url: 'noimage/:style.png',
                        url: '/spree/products/:id/:style/:basename.:extension',
                        path: ':rails_root/public/spree/products/:id/:style/:basename.:extension',
                        storage: :cloudinary,
                        cloudinary_credentials: Rails.root.join("config/cloudinary.yml"),
                        convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
      validates_attachment :attachment,
        presence: true,
        content_type: { content_type: %w[image/jpeg image/jpg image/png image/gif] }
      # save the w,h of the original image (from which others can be calculated)
      # we need to look at the write-queue for images which have not been saved yet
      after_post_process :find_dimensions, if: :valid?
    end
  end
  Spree::Image::PaperclipAttachment.prepend self
end 
```
there are no errors, and I used byebug to make sure the file is being used but still the images are being stored locally, so next I tried adding to the `Spree::Image.attachment_definitions[:attachment]` hash by using `Spree::Image.attachment_definitions[:attachment][:storage] = :cloudinary` I tried adding that in the initializer file, and within the decorator, yet still the images are saved on the device and when I run `Spree::Image.attachment_definitions[:attachment]` in the rails console I get
```
=> {:attachment=>
  {:styles=>{:mini=>"48x48>", :small=>"400x400>", :product=>"680x680>", :large=>"1200x1200>"},
   :default_style=>:product,
   :default_url=>"noimage/:style.png",
   :url=>"/spree/products/:id/:style/:basename.:extension",
   :path=>":rails_root/public/spree/products/:id/:style/:basename.:extension",
   :convert_options=>{:all=>"-strip -auto-orient -colorspace sRGB"}}}
```
showing that the configuration is still not being overridden

**Comment by kennyadsl** [comment]
I know that [solidus-demo](https://github.com/solidusio/solidus-demo/), which is the repo for the demo of Solidus, is using Cloudinary, maybe there's something there you can use to make it work, [this configuration](https://github.com/solidusio/solidus-demo/blob/f0bf3b7c4ec3f837202e6ef4f8a3c00f74744a20/config/initializers/paperclip.rb) for example.

**Comment by Shalashtein** [comment]
> I know that [solidus-demo](https://github.com/solidusio/solidus-demo/), which is the repo for the demo of Solidus, is using Cloudinary, maybe there's something there you can use to make it work, [this configuration](https://github.com/solidusio/solidus-demo/blob/f0bf3b7c4ec3f837202e6ef4f8a3c00f74744a20/config/initializers/paperclip.rb) for example.

Thank you, I'll start reading the code, see what I can do

**Comment by Shalashtein** [comment]
> I know that [solidus-demo](https://github.com/solidusio/solidus-demo/), which is the repo for the demo of Solidus, is using Cloudinary, maybe there's something there you can use to make it work, [this configuration](https://github.com/solidusio/solidus-demo/blob/f0bf3b7c4ec3f837202e6ef4f8a3c00f74744a20/config/initializers/paperclip.rb) for example.

Everything is working fine from the cloudinary-paperclip gem side, the problem is that I'm getting a 
`public_id (/...) is invalid`

This is due to the trailing slash in the begging of the :path value in the has_attchement hash, but the thing is I can't override this hash, I tried doing the same thing they did the demo app with the initializer file
```
require 'paperclip/cloudinary'

Paperclip::Attachment.default_options[:storage] = :cloudinary
Paperclip::Attachment.default_options[:public_url] = ":url"

Spree::Image.attachment_definitions[:attachment].delete(:url)
Spree::Image.attachment_definitions[:attachment].delete(:path)
Spree::Image.attachment_definitions[:attachment].delete(:default_url)
Spree::Image.attachment_definitions[:attachment][:path] = 'spree/products/:id/:style/:filename'
Spree::Image.attachment_definitions[:attachment][:cloudinary_url_options] = {
  default: { secure: true }
}

```
however only the 
`Paperclip::Attachment.default_options` 
is being updated while the 
`Spree::Image.attachment_definitions[:attachment]`
is not being updated

Here's the full trace in case you can help

```
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cloudinary-1.18.1/lib/cloudinary/uploader.rb:371:in `block in call_api'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:834:in `process_result'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http.rb:920:in `start'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cloudinary-1.18.1/lib/cloudinary/uploader.rb:358:in `call_api'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/cloudinary-1.18.1/lib/cloudinary/uploader.rb:79:in `upload'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-cloudinary-1.3.2/lib/paperclip/storage/cloudinary.rb:40:in `block in flush_writes'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-cloudinary-1.3.2/lib/paperclip/storage/cloudinary.rb:19:in `each'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-cloudinary-1.3.2/lib/paperclip/storage/cloudinary.rb:19:in `flush_writes'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-6.1.0/lib/paperclip/attachment.rb:246:in `save'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/paperclip-6.1.0/lib/paperclip/has_attached_file.rb:92:in `block in add_active_record_callbacks'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `instance_exec'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:238:in `block in halting_and_conditional'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `each'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `invoke_after'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:327:in `create_or_update'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/timestamp.rb:128:in `create_or_update'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:470:in `save'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:47:in `save'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `block in save'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `save'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:44:in `save'
/home/shalashtein/code/Shalashtein/labbesne/app/controllers/spree/admin/resource_controller_decorator.rb:17:in `create'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/abstract_controller/base.rb:195:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:180:in `block in instrument'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:180:in `instrument'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/abstract_controller/base.rb:136:in `process'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.0.3.4/lib/action_view/rendering.rb:39:in `process'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal.rb:190:in `dispatch'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_controller/metal.rb:254:in `dispatch'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:32:in `each'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:527:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/railtie.rb:190:in `public_send'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/railtie.rb:190:in `method_missing'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:32:in `each'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:567:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:132:in `call_app'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:28:in `block in call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `catch'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/rack/logger.rb:37:in `call_app'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/rack/logger.rb:26:in `block in call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/rack/logger.rb:26:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/static.rb:126:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.4/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:527:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/configuration.rb:228:in `call'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/server.rb:713:in `handle_request'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/server.rb:472:in `process_client'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/server.rb:328:in `block in run'
/home/shalashtein/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by kennyadsl** [comment]
Maybe there's something else in the initialization process that is updating `Spree::Image.attachment_definitions[:attachment]` later?

**Comment by Shalashtein** [comment]
For anyone else facing this in the future this is how I fixed it:

Copy the PaperclipAttachment module into app/models/spree/image/ rename it, edit the has_attachment hash then in the spree initializer edit the configuration of

```
config.image_attachment_module = 'Spree::Image::<your new module>'
config.taxon_attachment_module = 'Spree::Image::<your new module>'
```
