### ISSUE TITLE
NoMethodError raised in Spree::Api::BaseController#parameter_missing_error

### ISSUE THREAD

**Issue by dividedharmony** [solidusio/solidus#3941]
While working on https://github.com/solidusio-contrib/solidus_related_products/pull/88, I ran into a bug that causes every branch in that repository to fail its specs.

When it gets to 
```rb
# /api/app/controllers/spree/api/base_controller.rb:78
def parameter_missing_error(exception)
  message = exception.original_message || exception.message
  render json: {
    exception: message,
    error: message,
    missing_param: exception.param
  }, status: :unprocessable_entity
end
```
it throws a `NoMethodError: undefined method `original_message' for #<ActionController::ParameterMissing:0x00005562850cf908>` which obscures the original exception and causes what should be a 422 status response to be a 500 status response.

### Full Stack Trace:
```
Failure/Error: post :create, params: { product_id: product.id, variant_id: variant.id, token: user.spree_api_key, format: :json }

NoMethodError:
  undefined method `original_message' for #<ActionController::ParameterMissing:0x00005562850cf908>
./vendor/bundle/master/ruby/2.5.0/bundler/gems/solidus-70979e8dd1df/api/app/controllers/spree/api/base_controller.rb:79:in `parameter_missing_error'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/rescuable.rb:92:in `call'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/rescuable.rb:92:in `rescue_with_handler'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/rescuable.rb:165:in `rescue_with_handler'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/rescue.rb:25:in `rescue in process_action'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/rescue.rb:21:in `process_action'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:203:in `block in instrument'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
./vendor/bundle/master/ruby/2.5.0/gems/activesupport-6.1.2.1/lib/active_support/notifications.rb:203:in `instrument'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
./vendor/bundle/master/ruby/2.5.0/gems/activerecord-6.1.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/abstract_controller/base.rb:165:in `process'
./vendor/bundle/master/ruby/2.5.0/gems/actionview-6.1.2.1/lib/action_view/rendering.rb:39:in `process'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal.rb:190:in `dispatch'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/test_case.rb:577:in `process_controller_response'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/test_case.rb:496:in `process'
./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/test_case.rb:403:in `post'
./spec/controllers/spree/api/variants/relations_controller_spec.rb:54:in `block (4 levels) in <top (required)>'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-rails-4.0.2/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:ControllerExampleGroup>'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-rails-4.0.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
./vendor/bundle/master/ruby/2.5.0/gems/solidus_dev_support-2.4.0/lib/solidus_dev_support/rspec/rails_helper.rb:55:in `block (3 levels) in <top (required)>'
./vendor/bundle/master/ruby/2.5.0/gems/database_cleaner-1.99.0/lib/database_cleaner/generic/base.rb:16:in `cleaning'
./vendor/bundle/master/ruby/2.5.0/gems/database_cleaner-1.99.0/lib/database_cleaner/configuration.rb:88:in `block (2 levels) in cleaning'
./vendor/bundle/master/ruby/2.5.0/gems/database_cleaner-1.99.0/lib/database_cleaner/configuration.rb:89:in `cleaning'
./vendor/bundle/master/ruby/2.5.0/gems/solidus_dev_support-2.4.0/lib/solidus_dev_support/rspec/rails_helper.rb:52:in `block (2 levels) in <top (required)>'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
./vendor/bundle/master/ruby/2.5.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
------------------
--- Caused by: ---
ActionController::ParameterMissing:
  param is missing or the value is empty: relation
  ./vendor/bundle/master/ruby/2.5.0/gems/actionpack-6.1.2.1/lib/action_controller/metal/strong_parameters.rb:507:in `require'
```

**Solidus Version**:
This bug occurs with v2.11, v3.0, and master

**To Reproduce**
Reproducing this error is a bit difficult. I can't see to get this behavior locally, only on https://github.com/solidusio-contrib/solidus_related_products CircleCI. I suspect this either happens when running Solidus version >=`2.11` and Rails version < `6.1.0` OR because of weird load order issues.

**Current behavior**
The `NoMethodError` is raised causing a 500 status response.

**Expected behavior**
Missing parameters are caught and a 422 status response is returned.

**Comment by kennyadsl** [comment]
Thanks for reporting these details! 

I have one question:

>  I suspect this either happens when running Solidus version >=2.11 and Rails version < 6.1.0

How can you see this? In some failing CI (eg https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_related_products/104/workflows/f0c70134-479d-4089-9570-ff57be15cc2a/jobs/263/steps) I can see the error happening with `rails 6.1.1`, checking for example the [`Solidus v2.11: Install Gems` step](https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_related_products/104/workflows/f0c70134-479d-4089-9570-ff57be15cc2a/jobs/263/parallel-runs/0/steps/0-116).

**Comment by dividedharmony** [comment]
@kennyadsl I wasn't able to actually test for "Solidus version >=2.11 and Rails version < 6.1.0" circumstance.I just think it *could* happen with those two versions because 2.11 is when Solidus started using `#original_message` in the Api::BaseController:
https://github.com/solidusio/solidus/commit/dba286d89f5554f6e3b270c91209096250b8f801#diff-ed77272cb0f217c79746952e3b7689fabf33e67b0b8906aaeaf16836db9f6d50
and Rails v6.1.0 is when Rails added `DidYouMean` to `ParameterMissing`:
https://github.com/rails/rails/commit/5411565
