### ISSUE TITLE
Spree::Deprecator is not a valid constant in 2.11.5

### ISSUE THREAD

**Issue by tmtrademarked** [solidusio/solidus#3990]
Running specs in 2.11.5 produces an error about an unknown constant. It *appears* that the `core/lib/spree/testing_support.rb` file has a bug and should be using a different syntax: https://github.com/solidusio/solidus/blame/master/core/lib/spree/testing_support.rb#L28. It appears that this was introduced in the 2.11.5 patch.

**Solidus Version**:
2.11.5

**To Reproduce**
1. Update to 2.11.5
2. Run rspec tests using `bundle exec rspec`

**Current behavior**
```
Failure/Error: require File.expand_path('../config/environment', __dir__)

NameError:
  uninitialized constant Spree::Deprecator
  Did you mean?  Spree::Deprecation
                 Delegator
# ./config/application.rb:102:in `block in <class:Application>'
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:8:in `require'
# ./spec/rails_helper.rb:8:in `<top (required)>'
```

**Expected behavior**
No errors. :-)

**Comment by tmtrademarked** [comment]
I *think* this PR should fix this problem: https://github.com/solidusio/solidus/pull/3991
