### ISSUE TITLE
Unclear Guides

### ISSUE THREAD

**Issue by xeruf** [solidusio/solidus#4329]
So there seem to be two guides, and despite https://guides.solidus.io/developers/getting-started/first-time-installation.html apparently being canonical, I actually found the edge guides more clear: https://edgeguides.solidus.io/getting-started/what-is-solidus

But they seem highly redundant, and maybe the edge guides are also dated? I don't even know where their source files are.

Either way, a new, not yet supported rails version may come around any time, and robust instructions are needed for that (see also https://github.com/solidusio/solidus/issues/4277).
According to https://stackoverflow.com/questions/9479485/create-a-new-project-in-rails-older-version I tried:
```sh
gem install rails -v=6
rails _6_ new solidcluster --skip-javascript
```
But this ended up throwing an error:
```
❯ rails _6_ new solidcluster --skip-javascript
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /home/janek/data/1-projects/ftt/solidcluster/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
/home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:175:in `_encrypt'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:76:in `encrypt'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/encrypted_file.rb:50:in `write'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/activesupport-6.0.0/lib/active_support/encrypted_configuration.rb:29:in `write'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/generators/rails/credentials/credentials_generator.rb:30:in `add_credentials_file_silently'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/generators/rails/app/app_generator.rb:177:in `credentials'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/generators/app_base.rb:156:in `build'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/generators/rails/app/app_generator.rb:331:in `create_credentials'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/commands/application/application_command.rb:26:in `perform'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/lib/rails/cli.rb:18:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/janek/.local/share/gem/ruby/3.0.0/gems/railties-6.0.0/exe/rails:10:in `<top (required)>'
	from /home/janek/.local/share/gem/ruby/3.0.0/bin/rails:25:in `load'
	from /home/janek/.local/share/gem/ruby/3.0.0/bin/rails:25:in `<main>'
```

I am also dumbstruck by the instructions focusing on Macs, when Solidus as a webshop is supposed to run on a server, which of course runs Linux.
Despite my awe for this project, these factors do impede my initial trust in its maturity.

**Comment by kennyadsl** [comment]
Hello!

Thanks for the feedback. It appears to be an issue with Rails itself, you didn't install Solidus at all with that command, isn't it? Also, I tried the same command locally and it has been successful. 

I suppose it's an issue with the Ruby version you are using, maybe Rails 6.0.0 is not compatible with Ruby 3? I suggest you to try with Rails [6.1.5](https://rubygems.org/gems/rails/versions/6.1.5).

```
gem install rails -v=6.1.5
rails _6.1.5_ new solidcluster --skip-javascript
```

Let me know if this helps!

**Comment by jarednorman** [comment]
> So there seem to be two guides [...]

The edge guides are a work in progress, intending to replace the old guides. They aren't yet a complete replacement for the old guides.

> I am also dumbstruck by the instructions focusing on Macs, when Solidus as a webshop is supposed to run on a server, which of course runs Linux.

Those instructions are to help people not familiar with the tools get up and running quickly in a local development environment. It would be nice to have Linux instructions too, but these would need to vary from distribution to distribution. The edge guides have instructions around possible deployment configuration.

Regardless, running/deploying a Solidus app is no different than any other Rails app, so you can follow any instructions for deploying a Rails application to your platform of choice; you don't need something Solidus-specific.

> [...] these factors do impede my initial trust in its maturity.

I work with a variety of organizations doing hundreds of millions of dollars in sales through Solidus. No eCommerce platform is perfect and they all have their tradeoffs, but Solidus has been around for a long time now and is plenty mature.

---

Our issue tracker is for tracking Solidus bugs/features. Since you're struggling to install Rails, not Solidus, you may be better served by Rails-specific help channels. If you're struggling to troubleshoot an issue with Solidus, I recommend our [Troubleshooting discussion board](https://github.com/solidusio/solidus/discussions/categories/troubleshooting) or joining the Slack and using the #support channel there.

**Comment by xeruf** [comment]
right, I totally forgot that this command had nothing to do with solidus yet ^^
Indeed running `rails _6.1.5_ new solidcluster --skip-javascript` worked - I though specifying _6_ would default to the latest version with major 6, not the oldest...
