### ISSUE TITLE
Fail to install Solidus (with solidus starter frontend)

### ISSUE THREAD

**Issue by joyboy67** [solidusio/solidus#4582]
Hello, I have some issue when I try to install Solidus with starter frontend

**Solidus Version**:
3.2.0

**To Reproduce**
rails g solidus:install (with Y for solidus starter frontend)

**Current behavior**

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.1/gems/io-event-1.0.9/ext
/usr/local/bin/ruby31 -I /usr/local/lib/ruby/site_ruby/3.1 -r
./siteconf20220907-35220-ny28ez.rb extconf.rb
checking for rb_ext_ractor_safe()... yes
checking for &rb_fiber_transfer()... yes
checking for -luring... no
checking for sys/epoll.h... no
checking for sys/event.h... yes
checking for sys/eventfd.h... no
checking for rb_io_descriptor()... yes
checking for &rb_process_status_wait()... no
checking for rb_fiber_current()... yes
checking for &rb_fiber_raise()... yes
checking for ruby/io/buffer.h... yes
creating extconf.h
creating Makefile

current directory: /usr/local/lib/ruby/gems/3.1/gems/io-event-1.0.9/ext
make DESTDIR\= clean

current directory: /usr/local/lib/ruby/gems/3.1/gems/io-event-1.0.9/ext
make DESTDIR\=
compiling ./io/event/event.c
compiling ./io/event/selector/selector.c
compiling ./io/event/selector/kqueue.c
./io/event/selector/kqueue.c:193:50: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
        event.flags = EV_ADD | EV_ENABLE | EV_ONESHOT | EV_UDATA_SPECIFIC;
                                                        ^
./io/event/selector/kqueue.c:217:28: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
        event.flags = EV_DELETE | EV_UDATA_SPECIFIC;
                                  ^
./io/event/selector/kqueue.c:276:60: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
                kevents[count].flags = EV_ADD | EV_ENABLE | EV_ONESHOT | EV_UDATA_SPECIFIC;
                                                                         ^
./io/event/selector/kqueue.c:291:60: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
                kevents[count].flags = EV_ADD | EV_ENABLE | EV_ONESHOT | EV_UDATA_SPECIFIC;
                                                                         ^
./io/event/selector/kqueue.c:313:38: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
                kevents[count].flags = EV_DELETE | EV_UDATA_SPECIFIC;
                                                   ^
./io/event/selector/kqueue.c:321:38: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
                kevents[count].flags = EV_DELETE | EV_UDATA_SPECIFIC;
                                                   ^
./io/event/selector/kqueue.c:697:20: error: use of undeclared identifier 'EVFILT_USER'
                trigger.filter = EVFILT_USER;
                                 ^
./io/event/selector/kqueue.c:698:39: error: use of undeclared identifier 'EV_UDATA_SPECIFIC'
                trigger.flags = EV_ADD | EV_CLEAR | EV_UDATA_SPECIFIC;
                                                    ^
./io/event/selector/kqueue.c:699:20: error: use of undeclared identifier 'NOTE_TRIGGER'
                trigger.fflags = NOTE_TRIGGER;
                                 ^
9 errors generated.
*** Error 1 in /usr/local/lib/ruby/gems/3.1/gems/io-event-1.0.9/ext (Makefile:246 'kqueue.o':
@ cc -I. -I/usr/local/include/ruby-3.1/x86_64-...)

make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/3.1/gems/io-event-1.0.9 for
inspection.
Results logged to
/usr/local/lib/ruby/gems/3.1/extensions/x86_64-openbsd/3.1/io-event-1.0.9/gem_make.out

  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:95:in `run'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:44:in `block in make'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:36:in `each'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:36:in `make'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/ext_conf_builder.rb:63:in `block in build'
  /usr/local/lib/ruby/3.1/tempfile.rb:317:in `open'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:164:in `build_extension'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:198:in `block in build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:195:in `each'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/ext/builder.rb:195:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.1/rubygems/installer.rb:851:in `build_extensions'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/source/rubygems.rb:204:in
`install'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/worker.rb:62:in `apply_func'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/worker.rb:57:in `block in
process_queue'
  /usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/worker.rb:54:in `process_queue'
/usr/local/lib/ruby/gems/3.1/gems/bundler-2.3.15/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing io-event (1.0.9), and Bundler cannot continue.

In Gemfile:
  solidus_dev_support was resolved to 2.5.4, which depends on
    github_changelog_generator was resolved to 1.16.4, which depends on
      async-http-faraday was resolved to 0.11.0, which depends on
        async-http was resolved to 0.59.2, which depends on
          async-io was resolved to 1.34.0, which depends on
            async was resolved to 2.1.0, which depends on
              io-event
```

**Desktop (please complete the following information):**
 - Ruby version: 3.1.2
 - OS: OpenBSD 7.1 x64
 - Browser: Firefox 100

**Comment by gsmendoza** [comment]
Hi @joyboy67 ! Have you tried installing io-event 1.0.9 by itself i.e. `gem install io-event --version=1.0.9`?

**Comment by elia** [comment]
Also I'm wondering if there's a reason for having `solidus_dev_support` in the Gemfile, it's intended use is for helping in extension development, not for stores, is this error happening within an extension?

**Comment by waiting-for-dev** [comment]
Hey @joyboy67, moving it to the troubleshooting section on discussions. Please, let's follow up there.
