### ISSUE TITLE
Undefined method `register_engine' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by edenisn** [solidusio/solidus#598]
I use rails 4.2.5 and ruby 2.2.3 for my app. I try to run this command: `bundle exec rails g spree:install` and get the error:
```
/Users/edenisn/.rvm/gems/ruby-2.2.3/gems/handlebars_assets-0.22.0/lib/handlebars_assets.rb:20:in `block in register_extensions': undefined method `register_engine' for nil:NilClass (NoMethodError)
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/handlebars_assets-0.22.0/lib/handlebars_assets.rb:19:in `each'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/handlebars_assets-0.22.0/lib/handlebars_assets.rb:19:in `register_extensions'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/handlebars_assets-0.22.0/lib/handlebars_assets/engine.rb:5:in `block in <class:Engine>'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/edenisn/RubymineProjects/spree_demo/config/environment.rb:5:in `<top (required)>'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application.rb:92:in `preload'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application.rb:143:in `serve'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application.rb:131:in `block in run'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application.rb:125:in `loop'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application.rb:125:in `run'
	from /Users/edenisn/.rvm/gems/ruby-2.2.3/gems/spring-1.6.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/edenisn/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```
My gemfile:
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'solidus'
gem 'solidus_auth_devise'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

```
What's wrong?

**Comment by tka** [comment]
try to lock sprockets-rails version

ref. https://github.com/solidusio/solidus/commit/5988804b30805419e42d116a17746e0c22842ee4

**Comment by edenisn** [comment]
Thanks @tka

**Comment by magnusvk** [comment]
Closing this as this is now locked to a working version in master.

**Comment by varun-raj** [comment]
`bundle update` worked for me

**Comment by dt1973** [comment]
We can't lock Sprockets forever. Please see https://github.com/fnando/i18n-js/issues/381 -- was this the commit @PikachuEXE was referring to at the end? https://github.com/fnando/i18n-js/commit/f5dcfac7721938b3f5440e81565c79bd48b6aa09

**Comment by gmacdougall** [comment]
Hi @dt1973 Could you please move the issue of loosening the restriction on sprockets to a new issue?

We don't intended to keep sprockets locked forever, but it was breaking things significantly and needed to get a fix out fast.

**Comment by krishnasrihari** [comment]
bundle update works

**Comment by jstew529** [comment]
bundle update worked for me as well.

**Comment by jstew529** [comment]
bundle update worked for me as well.

**Comment by isantoshsingh** [comment]
bundle update worked for me too

**Comment by davidpatters0n** [comment]
also worked for me too. Maybe worth adding to the documentation maybe.

**Comment by jstew529** [comment]
^ second that

**Comment by gregblass** [comment]
Bundle update isn't doing the trick for me...

**Comment by olivierlacan** [comment]
@gregblass and others, don't try to update or lock sprockets. You need to change your configuration syntax to pass a block according to @rafaelfranca:

```ruby
Rails.application.config.assets.configure do |env|
  env.register_engine('.slim', Slim::Template)
end
```

https://github.com/rails/sprockets-rails/issues/292#issuecomment-165894932

Might be relevant to @magnusvk.

**Comment by Samira64** [comment]
bundle update worked for me too
