### ISSUE TITLE
Flaky capybara spec

### ISSUE THREAD

**Issue by jordan-brough** [solidusio/solidus#963]
The spec below failed [here](https://circleci.com/gh/solidusio/solidus/2454) and then passed [here](https://circleci.com/gh/solidusio/solidus/2455).  Is that anything worth looking into?

```
Failures:

  1) Order Details as Admin cart edit page can add tracking information
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit spree.cart_admin_order_path(order)
          
          Capybara::Poltergeist::DeadClient:
            PhantomJS client died while processing {"id":"e1c75b61-f73c-4aa9-afd1-09369651abae","name":"visit","args":["http://127.0.0.1:48888/admin/orders/R100/cart",30]}
          # ./spec/features/admin/orders/order_details_spec.rb:24:in `block (4 levels) in <top (required)>'

     1.2) Failure/Error: wait_for_ajax if RSpec.current_example.metadata[:js]
          
          RuntimeError:
            AJAX request took longer than 5 seconds.
          # /home/ubuntu/solidus/core/lib/spree/testing_support/capybara_ext.rb:102:in `wait_for_ajax'
          # ./spec/spec_helper.rb:88:in `block (2 levels) in <top (required)>'
```

**Comment by cbrunsdon** [comment]
I think phantomjs dies pretty randomly and uncontrollably on the CI, which will cause other issues.

Hawth is the expert, but I think the best way to move these forward is to figure out what is up with #806 and get our poltergeist updated.

**Comment by jhawthorn** [comment]
This is a phantomjs bug.
